# Generated by Django 5.2.5 on 2025-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('engine_capacity', models.DecimalField(decimal_places=1, default=1.6, max_digits=3, verbose_name='Объем двигателя (л)')),
                ('year', models.PositiveIntegerField(default=2020, verbose_name='Год выпуска')),
                ('category', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('hatchback', 'Хэтчбек'), ('coupe', 'Купе'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('wagon', 'Универсал'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
